/api/vu/account/login:
  x-swagger-router-controller: local.controller
  post:
    operationId: callback
    tags:
      - VU - Account
    summary: Signin
    description: Signin
    parameters:
      - name: username
        in: formData
        description: username
        required: true
        type: string
      - name: password
        in: formData
        description: password
        required: true
        type: string
        format: password
    responses:
      200:
        description: Success.
        schema:
          type: object
          properties:
            token:
              type: string
      422:
        $ref: "#/responses/auth-422"
      500:
        $ref: "#/responses/auth-500"
