/api/m/processes:
  x-swagger-router-controller: m.process.controller
  post:
    operationId: createProcess
    tags:
      - M/Processes
    summary: Create a process
    description: Create a process
    parameters:
      - name: processName
        in: formData
        type: string
        description: Process name
        required: true
    responses:
      201:
        description: Create a process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  get:
    operationId: getProcesses
    tags:
      - M/Processes
    summary: Get processes
    description: Get processes
    responses:
      200:
        description: Get processes
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}:
  x-swagger-router-controller: m.process.controller
  put:
    operationId: updateProcess
    tags:
      - M/Processes
    summary: Update a process
    description: Update a process
    parameters:
      - name: process
        in: path
        type: string
        description: Process ID
        required: true
      - name: processName
        in: formData
        type: string
        description: Process name
        required: true
    responses:
      200:
        description: Process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  delete:
    operationId: removeProcess
    tags:
      - M/Processes
    summary: Remove a process
    description: Remove a process
    parameters:
      - name: process
        in: path
        type: string
        description: Process ID
        required: true
    responses:
      204:
        description: Sin contenido
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/roles:
  x-swagger-router-controller: m.process.controller
  post:
    operationId: addRoleToProcess
    tags:
      - M/Processes
    summary: Add role to process
    description: Add role to process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: role
        in: formData
        description: Role ID
        required: true
        type: string
    responses:
      200:
        description: Get roles from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  get:
    operationId: getRolesByProcess
    tags:
      - M/Processes
    summary: Get roles from process
    description: Get roles from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
    responses:
      200:
        description: Get roles from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/roles/{role}:
  x-swagger-router-controller: m.process.controller
  put:
    operationId: updateRoleFromProcess
    tags:
      - M/Processes
    summary: Update role from process
    description: Update role from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: role
        in: path
        description: Role ID
        required: true
        type: string
      - name: name
        in: formData
        description: Role name
        required: true
        type: string
    responses:
      200:
        description: Get roles from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  delete:
    operationId: removeRoleFromProcess
    tags:
      - M/Processes
    summary: Remove role from process
    description: Remove role from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: role
        in: path
        description: Role ID
        required: true
        type: string
    responses:
      204:
        description: Sin contenido
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/steps:
  x-swagger-router-controller: m.process.controller
  post:
    operationId: addStepToProcess
    tags:
      - M/Processes
    summary: Add step to process
    description: Add step to process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: step
        in: formData
        description: P/Step ID
        required: true
        type: string
    responses:
      200:
        description: Get steps from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  get:
    operationId: getStepsFromProcess
    tags:
      - M/Processes
    summary: Get steps from process
    description: Get steps from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
    responses:
      200:
        description: Get steps from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/steps/{step}:
  x-swagger-router-controller: m.process.controller
  delete:
    operationId: removeStepToProcess
    tags:
      - M/Processes
    summary: Remove step to process
    description: Remove step to process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: step
        in: path
        description: M/Step ID
        required: true
        type: string
    responses:
      200:
        description: Get steps from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/variables:
  x-swagger-router-controller: m.process.controller
  post:
    operationId: addVariableToProcess
    tags:
      - M/Processes
    summary: Add variable to process
    description: Add variable to process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: variable
        in: formData
        description: Variable name
        type: string
        required: true
      - name: value
        in: formData
        description: Value
        type: string
        required: true
    responses:
      200:
        description: Add variable to process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  get:
    operationId: getVariablesByProcess
    tags:
      - M/Processes
    summary: Get variables from process
    description: Get variables from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
    responses:
      200:
        description: Get variables from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/processes/{process}/variables/{variable}:
  x-swagger-router-controller: m.process.controller
  put:
    operationId: updateVariableFromProcess
    tags:
      - M/Processes
    summary: Update variable from process
    description: Update variable from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: variable
        in: path
        description: Variable ID
        required: true
        type: string
      - name: name
        in: formData
        description: Variable name
        required: true
        type: string
      - name: value
        in: formData
        description: Value name
        required: true
        type: string
    responses:
      200:
        description: Get variables from process
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  delete:
    operationId: removeVariableFromProcess
    tags:
      - M/Processes
    summary: Remove variable from process
    description: Remove variable from process
    parameters:
      - name: process
        in: path
        description: Process ID
        required: true
        type: string
      - name: variable
        in: path
        description: Variable ID
        required: true
        type: string
    responses:
      204:
        description: Sin contenido
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
