/api/m/steps/{step}/fields:
  x-swagger-router-controller: m.step.controller
  post:
    operationId: addFieldToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Add field to step
    description: Add field to step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
      - name: nameField
        in: formData
        type: string
        description: Name field
        required: true
      - name: description
        in: formData
        type: string
        description: Description field
        required: false
      - name: type
        in: formData
        type: string
        description: Type field
        required: true
      - name: isRequired
        in: formData
        type: boolean
        description: The field is required?
        required: true
      - name: permissions
        description: Permissions
        in: formData
        type: array
        items: {}
    responses:
      200:
        description: Create new field
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  get:
    operationId: getFieldsFromStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Get fields from step
    description: Get fields from step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
    responses:
      200:
        description: Get fields from step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/fields/{field}:
  x-swagger-router-controller: m.step.controller
  put:
    operationId: updateFieldFromStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Update field from step
    description: Update field from step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
      - name: field
        in: path
        type: string
        description: Field ID
        required: true
      - name: nameField
        in: formData
        type: string
        description: Field name
        required: true
      - name: description
        in: formData
        type: string
        description: Description field
        required: false
      - name: type
        in: formData
        type: string
        description: Type field
        required: true
      - name: isRequired
        in: formData
        type: boolean
        description: The field is required?
        required: true
      - name: permissions
        description: Permissions
        in: formData
        type: array
        items: {}
    responses:
      200:
        description: Create new field
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
  delete:
    operationId: removeFieldFromStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Remove field from step
    description: Remove field from step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
      - name: field
        in: path
        type: string
        description: Field ID
        required: true
    responses:
      204:
        description: Remove new field
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/rules:
  x-swagger-router-controller: m.step.controller
  post:
    operationId: addRuleToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Add rule to step
    description: Add rule to step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
      - name: conditions
        description: Conditions
        in: formData
        type: array
        items: {}
      - name: callbacks
        description: Callbacks
        in: formData
        type: array
        items: {}
    responses:
      200:
        description: Add rule to step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/rules/{rule}:
  x-swagger-router-controller: m.step.controller
  delete:
    operationId: removeRuleToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Remove rule to step
    description: Remove rule to step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
      - name: rule
        in: path
        type: string
        description: Rule ID
        required: true
    responses:
      200:
        description: Remove rule to step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/roles:
  x-swagger-router-controller: m.step.controller
  post:
    operationId: addRoleToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Add role to step
    description: Add role to step
    parameters:
      - name: step
        in: path
        type: string
        description: PM - M/Step ID
        required: true
      - name: role
        description: VU - Role ID
        in: formData
        type: string
        required: true
    responses:
      200:
        description: Add role to step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/roles/{role}:
  x-swagger-router-controller: m.step.controller
  delete:
    operationId: removeRoleToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Remove role to step
    description: Remove role to step
    parameters:
      - name: step
        in: path
        type: string
        description: PM - M/Step ID
        required: true
      - name: role
        description: VU - Role ID
        in: path
        type: string
        required: true
    responses:
      200:
        description: Remove role to step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/origin:
  x-swagger-router-controller: m.step.controller
  put:
    operationId: setOriginStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Set origin step
    description: Set origin step
    parameters:
      - name: step
        in: path
        type: string
        description: Step ID
        required: true
    responses:
      200:
        description: Set origin step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/entities/{entity}:
  x-swagger-router-controller: m.step.controller
  put:
    operationId: setEntityToStep
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - PM - M/Steps
    summary: Set entity to step
    description: Set entity to step
    parameters:
      - name: step
        in: path
        type: string
        description: PM - M/Step ID
        required: true
      - name: entity
        description: VU - Entity ID
        in: path
        type: string
        required: true
    responses:
      200:
        description: Add entity to step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"

/api/m/steps/{step}/order:
  x-swagger-router-controller: m.step.controller
  get:
    operationId: getDataOrderStep
    security:
      - Bearer: []
    tags:
      - PM - M/Steps
    summary: Get data order step
    description: Get data order step
    parameters:
      - name: step
        in: path
        type: string
        description: PM - M/Step ID
        required: true
    responses:
      200:
        description: Get data order step
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
