/api/vu/account/login:
  x-swagger-router-controller: vu.account.controller
  post:
    operationId: login
    tags:
      - VU - Account
    summary: Autentication User
    description: Autentication User
    parameters:
      - name: username
        in: formData
        type: string
        description: Username
        required: true
      - name: password
        in: formData
        type: string
        format: password
        description: Password
        required: true
    responses:
      200:
        description: Get processes
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
