/api/vu/roles:
  x-swagger-router-controller: vu.role.controller
  get:
    operationId: getRoles
    security:
      - Bearer: []
    x-security-scopes:
      - 5d710564330f7d7cd67ee491
    tags:
      - VU - Roles
    summary: Get roles
    description: Get roles
    responses:
      200:
        description: Get roles
      500:
        description: Server error
        schema:
          $ref: "#/definitions/Error"
